import { Sparkles } from 'lucide-react';

import { Tooltip, TooltipContent, TooltipTrigger } from '@/app/components/ui/tooltip';
import type { MilestoneSource } from '@/types/milestone';
import { cn } from '../ui/utils';

interface MilestoneSourceBadgeProps {
    source: MilestoneSource;
    className?: string;
    /** Compact form drops the text label and keeps just the icon (for tight rows). */
    compact?: boolean;
}

/**
 * Marks a milestone that was generated from a meeting transcript via the AI
 * Project Planner. Renders nothing for `source === "manual"` milestones so
 * existing layouts are unaffected when the flag is off.
 */
export function MilestoneSourceBadge({
    source,
    className,
    compact = false,
}: MilestoneSourceBadgeProps) {
    if (source !== 'ai_meeting') return null;

    const icon = <Sparkles className="size-3 shrink-0" strokeWidth={2} aria-hidden />;

    if (compact) {
        return (
            <Tooltip>
                <TooltipTrigger asChild>
                    <span
                        className={cn(
                            'inline-flex size-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[#4f46e5]',
                            className,
                        )}
                        aria-label="Generated from a meeting"
                    >
                        {icon}
                    </span>
                </TooltipTrigger>
                <TooltipContent side="top">Generated from a meeting</TooltipContent>
            </Tooltip>
        );
    }

    return (
        <Tooltip>
            <TooltipTrigger asChild>
                <span
                    className={cn(
                        "inline-flex h-5 shrink-0 items-center gap-1 rounded-full bg-primary/10 px-2 font-['Satoshi',sans-serif] text-[10px] font-semibold uppercase tracking-wide text-[#4f46e5]",
                        className,
                    )}
                >
                    {icon}
                    From meeting
                </span>
            </TooltipTrigger>
            <TooltipContent side="top">
                Generated by the AI planner from a meeting transcript
            </TooltipContent>
        </Tooltip>
    );
}
